name: Time Series Analysis Classification pipelines
description: Do classification with preprocessed dataset
pipeline:
  - task: stratified_split
    id: strat_split
    input_id: input
    parameters: 
      important_feature: "AHU: Supply Air Temperature"  
      target_column: Fault Detection Ground Truth
  - task: fullyConnectedNN
    id: fullyConnectedNN
    input_id: strat_split
    parameters: 
      expected_file_name: "expected"
      predicted_file_name: "predicted"
      file_format: "csv"
      hidden_neurons: 30
  - task: evaluation
    id: eval
    input_id: fullyConnectedNN
    parameters: 
      eval_file_name: evaluation
      file_format: csv
      expected_file_name: expected
      predicted_file_name: predicted
      continuous: 0
      threshold: 0.5



