name: Time Series Analysis Preprocessing
description: Fault detection timeseries analysis preprocessing different datasets with different feature engineering
pipeline:

  - task: stratified_split
    id: stratified_split
    input_id: input
    parameters: 
      target_column: Label
      mode: multiclass

  - task: one_hot_encoding
    id: ohe
    input_id: stratified_split
    parameters:



  